import { round2, sumR } from './dinero.js';

export const CUSTOMER_LEDGER_KEY = 'bodega_customer_ledger_v1';
export const CUSTOMER_LEDGER_MIGRATION_KEY = 'customer_ledger_migration_v1';

export const CUSTOMER_MOVEMENT_TYPES = Object.freeze({
    INITIAL: 'SALDO_INICIAL_MIGRADO',
    DEBT_PAYMENT: 'ABONO_DEUDA',
    CREDIT_SALE: 'VENTA_FIADA',
    CREDIT_USED: 'SALDO_FAVOR_USADO',
    CHANGE_CREDITED: 'VUELTO_ACREDITADO',
    REFUND_CREDIT: 'DEVOLUCION_A_FAVOR',
    CREDIT_ADJUSTMENT: 'AJUSTE_CREDITO',
    DEBIT_ADJUSTMENT: 'AJUSTE_DEBITO',
    REVERSAL: 'ANULACION',
});

const CREDIT_TYPES = new Set([
    CUSTOMER_MOVEMENT_TYPES.INITIAL,
    CUSTOMER_MOVEMENT_TYPES.DEBT_PAYMENT,
    CUSTOMER_MOVEMENT_TYPES.CHANGE_CREDITED,
    CUSTOMER_MOVEMENT_TYPES.REFUND_CREDIT,
    CUSTOMER_MOVEMENT_TYPES.CREDIT_ADJUSTMENT,
]);

const DEBIT_TYPES = new Set([
    CUSTOMER_MOVEMENT_TYPES.CREDIT_SALE,
    CUSTOMER_MOVEMENT_TYPES.CREDIT_USED,
    CUSTOMER_MOVEMENT_TYPES.DEBIT_ADJUSTMENT,
]);

export function getCustomerBalance(customer) {
    const favor = Number.isFinite(Number(customer?.favor)) ? Number(customer.favor) : 0;
    const deuda = Number.isFinite(Number(customer?.deuda)) ? Number(customer.deuda) : 0;
    return round2(favor - deuda);
}

/**
 * Returns wallet credit generated by a product sale. A debt collection is a
 * customer payment (which may leave a credit balance), not a sale change, so
 * its legacy `vueltoParaMonedero` field must not be reported a second time.
 */
export function getGeneratedWalletCredit(sale) {
    if (!sale || sale.status === 'ANULADA') return 0;
    if (sale.tipo === 'COBRO_DEUDA') {
        return round2(Math.max(0, Number(sale.saldoFavorGeneradoUsd) || 0));
    }
    if (!['VENTA', 'VENTA_CASHEA'].includes(sale.tipo)) return 0;
    return round2(Math.max(0, Number(sale.vueltoParaMonedero) || 0));
}


export function snapshotCustomerBalance(customer, balance, { incrementVersion = true } = {}) {
    const normalizedBalance = round2(Number.isFinite(Number(balance)) ? Number(balance) : 0);
    return {
        ...customer,
        deuda: normalizedBalance < 0 ? round2(Math.abs(normalizedBalance)) : 0,
        favor: normalizedBalance > 0 ? normalizedBalance : 0,
        accountVersion: incrementVersion
            ? (Number(customer?.accountVersion) || 0) + 1
            : (Number(customer?.accountVersion) || 0),
        accountUpdatedAt: new Date().toISOString(),
    };
}

export function normalizeCustomer(customer) {
    const normalizedBalance = getCustomerBalance(customer);
    const canonicalCustomer = { ...(customer || {}) };
    delete canonicalCustomer.saldoFavor;
    const normalized = snapshotCustomerBalance(canonicalCustomer, normalizedBalance, { incrementVersion: false });
    // A migration/normalization must not accidentally modify Cashea.
    normalized.casheaDeuda = round2(Number(customer?.casheaDeuda) || 0);
    return normalized;
}

export function transitionCustomerBalance(customer, movement) {
    const amountUsd = round2(Number(movement?.amountUsd));
    if (!Number.isFinite(amountUsd) || amountUsd < 0) {
        throw new Error('El monto del movimiento de cartera es inválido.');
    }
    const signedAmount = movement?.direction === 'DEBIT' ? -amountUsd : amountUsd;
    return snapshotCustomerBalance(customer, sumR(getCustomerBalance(customer), signedAmount));
}

export function movementDirection(type, explicitDirection) {
    if (explicitDirection === 'CREDIT' || explicitDirection === 'DEBIT') return explicitDirection;
    if (CREDIT_TYPES.has(type)) return 'CREDIT';
    if (DEBIT_TYPES.has(type)) return 'DEBIT';
    throw new Error(`Tipo de movimiento de cartera desconocido: ${type}`);
}

export function createCustomerLedgerMovement({
    id,
    customerId,
    type,
    direction,
    amountUsd,
    balanceBeforeUsd,
    balanceAfterUsd,
    sourceType = 'MANUAL',
    sourceId,
    sourceSaleId = null,
    paymentMethodId = null,
    reason,
    user = null,
    timestamp = new Date().toISOString(),
    reversalOf = null,
    status = 'COMPLETED',
    migrationVersion = null,
}) {
    const amount = round2(Number(amountUsd));
    if (!customerId) throw new Error('El movimiento de cartera requiere customerId.');
    if (!type) throw new Error('El movimiento de cartera requiere type.');
    if (!Number.isFinite(amount) || amount < 0) throw new Error('El monto del movimiento de cartera es inválido.');

    return {
        id: id || (typeof crypto !== 'undefined' && crypto.randomUUID
            ? crypto.randomUUID()
            : `ledger_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`),
        customerId,
        type,
        direction: movementDirection(type, direction),
        amountUsd: amount,
        currency: 'USD',
        balanceBeforeUsd: round2(balanceBeforeUsd),
        balanceAfterUsd: round2(balanceAfterUsd),
        sourceType,
        sourceId: sourceId || null,
        sourceSaleId,
        paymentMethodId,
        reason: reason || type,
        userId: user?.id || user?.userId || 'SYSTEM',
        userName: user?.nombre || user?.name || user?.userName || 'Sistema',
        timestamp,
        reversalOf,
        status,
        ...(migrationVersion ? { migrationVersion } : {}),
    };
}

export function hasLedgerSource(ledger, sourceId) {
    return Boolean(sourceId && Array.isArray(ledger) && ledger.some(m => m.sourceId === sourceId));
}

export function calculateLedgerBalance(ledger, customerId) {
    const movements = (Array.isArray(ledger) ? ledger : [])
        .filter(m => m.customerId === customerId && m.status !== 'VOIDED');
    if (movements.length === 0) return 0;
    return round2(movements[movements.length - 1].balanceAfterUsd);
}

export function rebuildCustomersFromLedger(customers, ledger) {
    const entries = Array.isArray(ledger) ? ledger : [];
    return (Array.isArray(customers) ? customers : []).map(customer => {
        const movements = entries.filter(movement => movement.customerId === customer.id && movement.status !== 'VOIDED');
        if (movements.length === 0) return normalizeCustomer(customer);
        const last = movements[movements.length - 1];
        return snapshotCustomerBalance(customer, last.balanceAfterUsd, { incrementVersion: false });
    });
}

export function mergeLedgerEntries(localLedger, remoteLedger) {
    const merged = new Map();
    const conflicts = [];
    for (const entry of Array.isArray(localLedger) ? localLedger : []) {
        if (entry?.id) merged.set(entry.id, entry);
    }
    for (const entry of Array.isArray(remoteLedger) ? remoteLedger : []) {
        if (!entry?.id) continue;
        const local = merged.get(entry.id);
        if (local && JSON.stringify(local) !== JSON.stringify(entry)) {
            conflicts.push({ id: entry.id, local, remote: entry });
            continue;
        }
        merged.set(entry.id, entry);
    }
    const ledger = [...merged.values()].sort((left, right) => {
        const byDate = String(left.timestamp || '').localeCompare(String(right.timestamp || ''));
        return byDate || String(left.id).localeCompare(String(right.id));
    });
    return { ledger, conflicts };
}
